export const weatherIconMap: Record<string, string> = {
  'Sunny': '/sunny.png',
  'Partly Cloudy': '/cloudy_day.png',
  'Overcast': '/cloudy.png',
  'Cloudy': '/cloudy.png',
  'Light drizzle': '/rain.png',
  'Patchy light drizzle': '/rain.png',
  'Light freezing rain': '/rain.png',
  'Light rain': '/rain.png',
  'Moderate rain': '/rain.png',
  'Heavy rain': '/rain.png',
  'Patchy rain nearby': '/rain.png',
  'Light rain shower': '/rain.png',
  'Light sleet showers': '/snow.png',
  'Light sleet': '/snow.png',
  'Light snow': '/snow.png',
  'Moderate snow': '/snow.png',
  'Heavy snow': '/snow.png',
  'Ice pellets': '/hail.png',
}

export const weatherBgMap: Record<string, string> = {
  'Sunny': '/sunny_bg.png',
  'Partly Cloudy': '/Cloudy_day_background.png',
  'Overcast': '/Cloudy_day_background.png',
  'Cloudy': '/Cloudy_day_background.png',
  'Light drizzle': '/Rain_background.png',
  'Patchy light drizzle': '/Rain_background.png',
  'Light freezing rain': '/Rain_background.png',
  'Light rain': '/Rain_background.png',
  'Moderate rain': '/Rain_background.png',
  'Heavy rain': '/Rain_background.png',
  'Patchy rain nearby': '/Rain_background.png',
  'Light rain shower': '/Rain_background.png',
  'Light sleet showers': '/Snow_background.png',
  'Light sleet': '/Snow_background.png',
  'Light snow': '/Snow_background.png',
  'Moderate snow': '/Snow_background.png',
  'Heavy snow': '/Snow_background.png',
  'Ice pellets': '/Hail_background.png',
}

const blueGradient = 'linear-gradient(to bottom, rgb(145, 182, 253) 30%, rgb(63, 126, 245))';
const purpleGradient = 'linear-gradient(to bottom, rgb(131, 154, 239) 30%, rgb(95, 76, 219))';


export const weatherGradient: Record<string, string> = {
  'Sunny': blueGradient,
  'Partly Cloudy': blueGradient,
  'Overcast': purpleGradient,
  'Cloudy': purpleGradient,
  'Light drizzle': purpleGradient,
  'Patchy light drizzle': purpleGradient,
  'Light freezing rain': purpleGradient,
  'Light rain': purpleGradient,
  'Moderate rain': purpleGradient,
  'Heavy rain': purpleGradient,
  'Patchy rain nearby': purpleGradient,
  'Light rain shower': purpleGradient,
  'Light sleet showers': purpleGradient,
  'Light sleet': purpleGradient,
  'Light snow': purpleGradient,
  'Moderate snow': purpleGradient,
  'Heavy snow': purpleGradient,
  'Ice pellets': purpleGradient,
}
